"""create v1 tables

Revision ID: 3f1b814ba137
Revises: 
Create Date: 2026-06-26 08:48:16.234462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1b814ba137'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('BEACH', 'HIKE', 'RUM_DISTILLERY', 'RESTAURANT', 'ACTIVITY', 'EVENT', 'ACCOMMODATION', name='category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('age_range', sa.Enum('UNDER_18', 'R18_25', 'R26_35', 'R36_50', 'R51_65', 'OVER_65', name='agerange'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('beach_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_of_interest_id', sa.Integer(), nullable=False),
    sa.Column('tourist_score', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['point_of_interest_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_of_interest_id')
    )
    op.create_table('hike_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_of_interest_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=True),
    sa.Column('elevation_gain', sa.Integer(), nullable=True),
    sa.Column('elevation_loss', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['point_of_interest_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_of_interest_id')
    )
    op.create_table('travel_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travel_project_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('travel_project_id', sa.Integer(), nullable=False),
    sa.Column('point_of_interest_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'CONFIRMED', 'DONE', name='itemstatus'), nullable=False),
    sa.ForeignKeyConstraint(['point_of_interest_id'], ['points_of_interest.id'], ),
    sa.ForeignKeyConstraint(['travel_project_id'], ['travel_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_project_items')
    op.drop_table('travel_projects')
    op.drop_table('hike_details')
    op.drop_table('beach_details')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('points_of_interest')
    # ### end Alembic commands ###
