"""add poi_images table

Revision ID: 93ca07e02899
Revises: 9f549fb13136
Create Date: 2026-08-23 17:33:19.102640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93ca07e02899'
down_revision: Union[str, None] = '9f549fb13136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poi_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poi_id'], ['points_of_interest.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poi_images_id'), 'poi_images', ['id'], unique=False)
    op.create_index(op.f('ix_poi_images_poi_id'), 'poi_images', ['poi_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_poi_images_poi_id'), table_name='poi_images')
    op.drop_index(op.f('ix_poi_images_id'), table_name='poi_images')
    op.drop_table('poi_images')
    # ### end Alembic commands ###
