"""add image_url to points_of_interest

Revision ID: 9f549fb13136
Revises: 3f1b814ba137
Create Date: 2026-08-21 19:11:53.386939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f549fb13136'
down_revision: Union[str, None] = '3f1b814ba137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('points_of_interest', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('points_of_interest', 'image_url')
    # ### end Alembic commands ###
