"""add restaurant details table

Revision ID: bfffcd99a7d6
Revises: d07cc5acde44
Create Date: 2026-09-17 10:58:26.036995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfffcd99a7d6'
down_revision: Union[str, None] = 'd07cc5acde44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_of_interest_id', sa.Integer(), nullable=False),
    sa.Column('cuisine', sa.String(length=120), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('michelin_distinction', sa.String(length=60), nullable=True),
    sa.Column('hotel_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['point_of_interest_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_of_interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_details')
    # ### end Alembic commands ###
