"""add rum distillery details table

Revision ID: d07cc5acde44
Revises: 93ca07e02899
Create Date: 2026-09-16 09:22:57.069888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd07cc5acde44'
down_revision: Union[str, None] = '93ca07e02899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rum_distillery_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('point_of_interest_id', sa.Integer(), nullable=False),
    sa.Column('tourist_score', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('visit_access', sa.Text(), nullable=True),
    sa.Column('pets_allowed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['point_of_interest_id'], ['points_of_interest.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('point_of_interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rum_distillery_details')
    # ### end Alembic commands ###
